/**
 * IttyBitz cryptography regression suite.
 *
 * `src/lib/crypto.ts` is FROZEN: people hold long-horizon (25-year) secrets
 * encrypted with it. This script is the gate that proves it still behaves.
 * Run it after ANY dependency bump, toolchain change, or refactor:
 *
 *     npm run test:crypto
 *
 * ── What makes this suite meaningful ────────────────────────────────────
 * The fixtures in `crypto-fixtures.json` are ciphertexts produced by the
 * REAL `src/lib/crypto.ts` from each tagged release, extracted from git
 * history and executed directly. They are historical artifacts, not values
 * regenerated by the code under test, so they catch what round-trip tests
 * cannot: encrypt and decrypt changing together in a way that stays
 * self-consistent but can no longer read what already shipped.
 *
 * Two wire formats exist in the wild and both are covered:
 *   v0  salt(16) || IV(12) || ciphertext                    (v1.0 – v1.4.0)
 *   v1  "IBTZ" || 0x01 || salt(16) || IV(12) || ciphertext  (v2.0.0 – now)
 *
 * Key derivation has never changed: PBKDF2-SHA256 @ 1,000,000 iterations,
 * AES-256-GCM, password bytes UTF-8, optional key file appended after the
 * password bytes. Verified identical from v1.0 to HEAD.
 *
 * Adding fixtures: APPEND to crypto-fixtures.json. Never modify or delete an
 * existing entry — each one is a promise that a real user's file still opens.
 *
 * The password and key file in the fixtures are TEST-ONLY and published in
 * this repo. Treat them as compromised; never use them for real data.
 */
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { webcrypto } from "node:crypto";
import { encryptFile, decryptFile } from "../src/lib/crypto.ts";

const HERE = dirname(fileURLToPath(import.meta.url));
const FIXTURES = JSON.parse(readFileSync(join(HERE, "crypto-fixtures.json"), "utf8"));

const enc = new TextEncoder();
const dec = new TextDecoder();

let failures = 0;
let passed = 0;
function check(condition: boolean, label: string) {
  if (condition) {
    passed++;
    console.log(`  ok    ${label}`);
  } else {
    failures++;
    console.error(`  FAIL  ${label}`);
  }
}

function b64ToArrayBuffer(b64: string): ArrayBuffer {
  const buf = Buffer.from(b64, "base64");
  return buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength) as ArrayBuffer;
}

function hexToArrayBuffer(hex: string): ArrayBuffer {
  const out = new Uint8Array(hex.length / 2);
  for (let i = 0; i < out.length; i++) out[i] = parseInt(hex.substr(i * 2, 2), 16);
  return out.buffer as ArrayBuffer;
}

async function main() {
  console.log("\nIttyBitz crypto regression\n");

  // ---- 1. Historical fixtures: the backward-compatibility guarantee ----
  const versions = [...new Set(FIXTURES.fixtures.map((f: any) => f.version))];
  console.log(
    `Historical ciphertexts (${FIXTURES.fixtures.length} fixtures from ${versions.length} releases: ${versions.join(", ")}):`
  );
  for (const fx of FIXTURES.fixtures) {
    const label = `${fx.version} [${fx.format}] ${fx.payload}${fx.keyFile ? " +keyfile" : ""}`;
    try {
      const keyFile = fx.keyFile ? hexToArrayBuffer(FIXTURES.keyFileHex) : null;
      const plaintext = dec.decode(
        await decryptFile(b64ToArrayBuffer(fx.base64), FIXTURES.password, keyFile)
      );
      check(plaintext === fx.plaintext, label);
      if (plaintext !== fx.plaintext) {
        console.error(`        expected: ${JSON.stringify(fx.plaintext)}`);
        console.error(`        actual:   ${JSON.stringify(plaintext)}`);
      }
    } catch (err) {
      check(false, `${label} — threw: ${(err as Error).message}`);
    }
  }

  // Independently-constructed v0 blob (raw Web Crypto, not this repo's code).
  console.log("\nIndependent construction (raw Web Crypto, not via crypto.ts):");
  try {
    const pt = dec.decode(
      await decryptFile(b64ToArrayBuffer(FIXTURES.independent.base64), FIXTURES.password, null)
    );
    check(pt === FIXTURES.independent.plaintext, "v0 layout built from raw primitives");
  } catch (err) {
    check(false, `v0 raw-primitive layout — threw: ${(err as Error).message}`);
  }

  // ---- 2. Round-trips ----
  console.log("\nRound-trips:");
  const secret = "couch easy language swap round-trip check";
  const ct = await encryptFile(enc.encode(secret).buffer as ArrayBuffer, FIXTURES.password, null);
  check(
    dec.decode(await decryptFile(ct.slice(0), FIXTURES.password, null)) === secret,
    "text round-trip"
  );

  const payload = new Uint8Array(4096);
  webcrypto.getRandomValues(payload);
  const payloadCopy = payload.slice(0);
  const keyFile = new Uint8Array(64);
  webcrypto.getRandomValues(keyFile);
  const ctKf = await encryptFile(
    payload.buffer.slice(0) as ArrayBuffer,
    FIXTURES.password,
    keyFile.buffer.slice(0) as ArrayBuffer
  );
  const ptKf = new Uint8Array(
    await decryptFile(ctKf.slice(0), FIXTURES.password, keyFile.buffer.slice(0) as ArrayBuffer)
  );
  check(
    ptKf.length === payloadCopy.length && ptKf.every((b, i) => b === payloadCopy[i]),
    "binary round-trip with key file"
  );

  const unicode = "秘密 · émoji 🔐🦖 · Ω≈ç√ · naïve café — “quoted”";
  const ctU = await encryptFile(enc.encode(unicode).buffer as ArrayBuffer, FIXTURES.password, null);
  check(
    dec.decode(await decryptFile(ctU.slice(0), FIXTURES.password, null)) === unicode,
    "unicode round-trip"
  );

  // ---- 3. Container layout ----
  console.log("\nContainer format:");
  const head = new Uint8Array(ct.slice(0, 5));
  check(
    head[0] === 0x49 && head[1] === 0x42 && head[2] === 0x54 && head[3] === 0x5a,
    'magic bytes are "IBTZ"'
  );
  check(head[4] === 0x01, "format version byte is 1");
  check(ct.byteLength > 5 + 16 + 12, "header + salt(16) + IV(12) + ciphertext present");

  // ---- 4. Negative cases ----
  console.log("\nRejections:");
  const rejects = async (label: string, fn: () => Promise<unknown>) => {
    try {
      await fn();
      check(false, `${label} (unexpectedly succeeded)`);
    } catch {
      check(true, label);
    }
  };

  await rejects("wrong password rejected", () =>
    decryptFile(ct.slice(0), FIXTURES.password + "wrong", null)
  );
  await rejects("wrong key file rejected", () => {
    const wrongKey = new Uint8Array(64);
    webcrypto.getRandomValues(wrongKey);
    return decryptFile(ctKf.slice(0), FIXTURES.password, wrongKey.buffer as ArrayBuffer);
  });
  await rejects("missing key file rejected", () =>
    decryptFile(ctKf.slice(0), FIXTURES.password, null)
  );
  await rejects("tampered ciphertext rejected (AES-GCM authentication)", () => {
    const tampered = new Uint8Array(ct.slice(0));
    tampered[tampered.length - 1] ^= 0xff;
    return decryptFile(tampered.buffer as ArrayBuffer, FIXTURES.password, null);
  });
  await rejects("tampered salt rejected", () => {
    const tampered = new Uint8Array(ct.slice(0));
    tampered[6] ^= 0xff; // inside the salt
    return decryptFile(tampered.buffer as ArrayBuffer, FIXTURES.password, null);
  });
  await rejects("truncated input rejected", () =>
    decryptFile(ct.slice(0, 20), FIXTURES.password, null)
  );

  // ---- Summary ----
  console.log(`\n${passed} passed, ${failures} failed`);
  if (failures > 0) {
    console.error("CRYPTO REGRESSION FAILED — do not ship.\n");
    process.exit(1);
  }
  console.log("All crypto regression checks passed.\n");
}

main().catch((err) => {
  console.error("\nFATAL:", err);
  process.exit(1);
});
