/**
 * IttyBitz cryptography regression suite.
 *
 * `src/lib/crypto.ts` is FROZEN: people hold long-horizon (25-year) secrets
 * encrypted with it. This script is the gate that proves it still behaves.
 * Run it after ANY dependency bump, toolchain change, or refactor:
 *
 *     npm run test:crypto
 *
 * The two most important checks are the FIXTURES below: real ciphertexts
 * produced by earlier builds and checked into the repo. They are external
 * artifacts, not values regenerated by the code under test, so they catch a
 * class of breakage that round-trip tests cannot — namely, encrypt and
 * decrypt changing together in a way that stays self-consistent but can no
 * longer read what shipped.
 *
 * Adding a fixture: whenever the format changes, append a new entry rather
 * than replacing an old one. Old entries must keep passing forever.
 *
 * The password below is TEST-ONLY and published in this repo. Treat it as
 * compromised; never use it for real data.
 */
import { encryptFile, decryptFile } from "../src/lib/crypto.ts";
import { webcrypto } from "node:crypto";

const TEST_PASSWORD = "Test-Password-For-Verification-Only-2026!";

/** Real ciphertexts from earlier releases. These must decrypt forever. */
const FIXTURES = [
  {
    name: "v1 IBTZ container (produced by the v2.7.0 build, TypeScript 5.9.3)",
    base64:
      "SUJUWgHwox2Um99Cy51Zos/GfsP2Tez5ojHYWbJAW0Jra45BmYEhVCQRECW7bW8A57dTtt/BXTvE6CbzI4O10lS6mWlsAlF2d0NvWYSbFJ9A3nKY2ERxYMxI+edbM6S4/rXLu9KpaEVpRFpjChO5mk3AIwfrBGOGRuTh5U+HQAVi6hACF3W5BKtUzZn3qw==",
    password: TEST_PASSWORD,
    expected:
      "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about",
  },
  {
    name: "v0 legacy headerless container (salt || iv || ciphertext, no IBTZ magic)",
    base64:
      "AEqF+xtkNZjrvhJ39wwUOAv+3mUV7X62jQ5XLXD5D00qg3OZKX5HELU/W6nrtLOpsbOj7Rxl2mAVkKiJ7xNvE1hjJmrFVaPk5Wi9pk44opKBcTgvdVBFWD2t7/wcqSc2+A==",
    password: TEST_PASSWORD,
    expected: "legacy v0 headerless fixture — must decrypt forever",
  },
] as const;

const enc = new TextEncoder();
const dec = new TextDecoder();

let failures = 0;
function check(condition: boolean, label: string) {
  if (condition) {
    console.log(`  ok  ${label}`);
  } else {
    console.error(`  FAIL  ${label}`);
    failures++;
  }
}

function base64ToBuffer(b64: string): ArrayBuffer {
  const bin = Buffer.from(b64, "base64");
  return bin.buffer.slice(bin.byteOffset, bin.byteOffset + bin.byteLength) as ArrayBuffer;
}

async function main() {
  console.log("\nIttyBitz crypto regression\n");

  // ---- 1. Checked-in fixtures: the real backward-compatibility guarantee ----
  console.log("Fixtures (ciphertexts from earlier builds):");
  for (const fx of FIXTURES) {
    try {
      const plaintext = dec.decode(await decryptFile(base64ToBuffer(fx.base64), fx.password, null));
      check(plaintext === fx.expected, fx.name);
      if (plaintext !== fx.expected) {
        console.error(`        expected: ${JSON.stringify(fx.expected)}`);
        console.error(`        actual:   ${JSON.stringify(plaintext)}`);
      }
    } catch (err) {
      check(false, `${fx.name} — threw: ${(err as Error).message}`);
    }
  }

  // ---- 2. Round-trips ----
  console.log("\nRound-trips:");
  const secret = "couch easy language swap round-trip check";
  const ct = await encryptFile(enc.encode(secret).buffer as ArrayBuffer, TEST_PASSWORD, null);
  check(dec.decode(await decryptFile(ct.slice(0), TEST_PASSWORD, null)) === secret, "text round-trip");

  const payload = new Uint8Array(4096);
  webcrypto.getRandomValues(payload);
  const payloadCopy = payload.slice(0);
  const keyFile = new Uint8Array(64);
  webcrypto.getRandomValues(keyFile);
  const ctKf = await encryptFile(
    payload.buffer.slice(0) as ArrayBuffer,
    TEST_PASSWORD,
    keyFile.buffer.slice(0) as ArrayBuffer
  );
  const ptKf = new Uint8Array(
    await decryptFile(ctKf.slice(0), TEST_PASSWORD, keyFile.buffer.slice(0) as ArrayBuffer)
  );
  check(
    ptKf.length === payloadCopy.length && ptKf.every((b, i) => b === payloadCopy[i]),
    "binary round-trip with key file"
  );

  // ---- 3. Container layout: IBTZ\x01 || salt(16) || IV(12) || ciphertext ----
  console.log("\nContainer format:");
  const head = new Uint8Array(ct.slice(0, 5));
  check(
    head[0] === 0x49 && head[1] === 0x42 && head[2] === 0x54 && head[3] === 0x5a,
    'magic bytes are "IBTZ"'
  );
  check(head[4] === 0x01, "format version byte is 1");
  check(ct.byteLength > 5 + 16 + 12, "header + salt(16) + IV(12) + ciphertext present");

  // ---- 4. Negative cases: these MUST fail ----
  console.log("\nRejections:");
  const rejects = async (label: string, fn: () => Promise<unknown>) => {
    try {
      await fn();
      check(false, `${label} (unexpectedly succeeded)`);
    } catch {
      check(true, label);
    }
  };

  await rejects("wrong password rejected", () =>
    decryptFile(ct.slice(0), TEST_PASSWORD + "wrong", null)
  );
  await rejects("wrong key file rejected", () => {
    const wrongKey = new Uint8Array(64);
    webcrypto.getRandomValues(wrongKey);
    return decryptFile(ctKf.slice(0), TEST_PASSWORD, wrongKey.buffer as ArrayBuffer);
  });
  await rejects("tampered ciphertext rejected (AES-GCM authentication)", () => {
    const tampered = new Uint8Array(ct.slice(0));
    tampered[tampered.length - 1] ^= 0xff;
    return decryptFile(tampered.buffer as ArrayBuffer, TEST_PASSWORD, null);
  });
  await rejects("truncated input rejected", () =>
    decryptFile(ct.slice(0, 20), TEST_PASSWORD, null)
  );

  // ---- Summary ----
  if (failures > 0) {
    console.error(`\n${failures} CHECK(S) FAILED — do not ship.\n`);
    process.exit(1);
  }
  console.log("\nAll crypto regression checks passed.\n");
}

main().catch((err) => {
  console.error("\nFATAL:", err);
  process.exit(1);
});
