/**
 * IttyBitz cryptography regression suite.
 *
 * `src/lib/crypto.ts` is FROZEN: people hold long-horizon (25-year) secrets
 * encrypted with it. This script is the gate that proves it still behaves.
 * Run it after ANY dependency bump, toolchain change, or refactor:
 *
 *     npm run test:crypto
 *
 * ── What makes this suite meaningful ────────────────────────────────────
 * The fixtures in `crypto-fixtures.json` are ciphertexts produced by the
 * REAL `src/lib/crypto.ts` from each tagged release, extracted from git
 * history and executed directly. They are historical artifacts, not values
 * regenerated by the code under test, so they catch what round-trip tests
 * cannot: encrypt and decrypt changing together in a way that stays
 * self-consistent but can no longer read what already shipped.
 *
 * Two wire formats exist in the wild and both are covered:
 *   v0  salt(16) || IV(12) || ciphertext                    (v1.0 – v1.4.0)
 *   v1  "IBTZ" || 0x01 || salt(16) || IV(12) || ciphertext  (v2.0.0 – now)
 *
 * Key derivation has never changed: PBKDF2-SHA256 @ 1,000,000 iterations,
 * AES-256-GCM, password bytes UTF-8, optional key file appended after the
 * password bytes. Verified identical from v1.0 to HEAD.
 *
 * Adding fixtures: APPEND to crypto-fixtures.json. Never modify or delete an
 * existing entry — each one is a promise that a real user's file still opens.
 *
 * The password and key file in the fixtures are TEST-ONLY and published in
 * this repo. Treat them as compromised; never use them for real data.
 *
 * Section 5 covers src/lib/bip39.ts. It is not part of the frozen core, but
 * a wrong word index yields a SeedQR that scans cleanly into the WRONG
 * wallet — silent and unrecoverable — so it is gated here too.
 */
import { readFileSync } from "node:fs";
import { createContext, runInContext } from "node:vm";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { webcrypto } from "node:crypto";
import { encryptFile, decryptFile } from "../src/lib/crypto.ts";
import { validateBip39, toStandardSeedQR } from "../src/lib/bip39.ts";

const HERE = dirname(fileURLToPath(import.meta.url));
const FIXTURES = JSON.parse(readFileSync(join(HERE, "crypto-fixtures.json"), "utf8"));

const enc = new TextEncoder();
const dec = new TextDecoder();

let failures = 0;
let passed = 0;
function check(condition: boolean, label: string) {
  if (condition) {
    passed++;
    console.log(`  ok    ${label}`);
  } else {
    failures++;
    console.error(`  FAIL  ${label}`);
  }
}

function b64ToArrayBuffer(b64: string): ArrayBuffer {
  const buf = Buffer.from(b64, "base64");
  return buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength) as ArrayBuffer;
}

function hexToArrayBuffer(hex: string): ArrayBuffer {
  const out = new Uint8Array(hex.length / 2);
  for (let i = 0; i < out.length; i++) out[i] = parseInt(hex.substr(i * 2, 2), 16);
  return out.buffer as ArrayBuffer;
}

async function main() {
  console.log("\nIttyBitz crypto regression\n");

  // ---- 1. Historical fixtures: the backward-compatibility guarantee ----
  const versions = [...new Set(FIXTURES.fixtures.map((f: any) => f.version))];
  console.log(
    `Historical ciphertexts (${FIXTURES.fixtures.length} fixtures from ${versions.length} releases: ${versions.join(", ")}):`
  );
  for (const fx of FIXTURES.fixtures) {
    const label = `${fx.version} [${fx.format}] ${fx.payload}${fx.keyFile ? " +keyfile" : ""}`;
    try {
      const keyFile = fx.keyFile ? hexToArrayBuffer(FIXTURES.keyFileHex) : null;
      const plaintext = dec.decode(
        await decryptFile(b64ToArrayBuffer(fx.base64), FIXTURES.password, keyFile)
      );
      check(plaintext === fx.plaintext, label);
      if (plaintext !== fx.plaintext) {
        console.error(`        expected: ${JSON.stringify(fx.plaintext)}`);
        console.error(`        actual:   ${JSON.stringify(plaintext)}`);
      }
    } catch (err) {
      check(false, `${label} — threw: ${(err as Error).message}`);
    }
  }

  // Independently-constructed v0 blob (raw Web Crypto, not this repo's code).
  console.log("\nIndependent construction (raw Web Crypto, not via crypto.ts):");
  try {
    const pt = dec.decode(
      await decryptFile(b64ToArrayBuffer(FIXTURES.independent.base64), FIXTURES.password, null)
    );
    check(pt === FIXTURES.independent.plaintext, "v0 layout built from raw primitives");
  } catch (err) {
    check(false, `v0 raw-primitive layout — threw: ${(err as Error).message}`);
  }

  // ---- 2. Round-trips ----
  console.log("\nRound-trips:");
  const secret = "couch easy language swap round-trip check";
  const ct = await encryptFile(enc.encode(secret).buffer as ArrayBuffer, FIXTURES.password, null);
  check(
    dec.decode(await decryptFile(ct.slice(0), FIXTURES.password, null)) === secret,
    "text round-trip"
  );

  const payload = new Uint8Array(4096);
  webcrypto.getRandomValues(payload);
  const payloadCopy = payload.slice(0);
  const keyFile = new Uint8Array(64);
  webcrypto.getRandomValues(keyFile);
  const ctKf = await encryptFile(
    payload.buffer.slice(0) as ArrayBuffer,
    FIXTURES.password,
    keyFile.buffer.slice(0) as ArrayBuffer
  );
  const ptKf = new Uint8Array(
    await decryptFile(ctKf.slice(0), FIXTURES.password, keyFile.buffer.slice(0) as ArrayBuffer)
  );
  check(
    ptKf.length === payloadCopy.length && ptKf.every((b, i) => b === payloadCopy[i]),
    "binary round-trip with key file"
  );

  const unicode = "秘密 · émoji 🔐🦖 · Ω≈ç√ · naïve café — “quoted”";
  const ctU = await encryptFile(enc.encode(unicode).buffer as ArrayBuffer, FIXTURES.password, null);
  check(
    dec.decode(await decryptFile(ctU.slice(0), FIXTURES.password, null)) === unicode,
    "unicode round-trip"
  );

  // ---- 3. Container layout ----
  console.log("\nContainer format:");
  const head = new Uint8Array(ct.slice(0, 5));
  check(
    head[0] === 0x49 && head[1] === 0x42 && head[2] === 0x54 && head[3] === 0x5a,
    'magic bytes are "IBTZ"'
  );
  check(head[4] === 0x01, "format version byte is 1");
  check(ct.byteLength > 5 + 16 + 12, "header + salt(16) + IV(12) + ciphertext present");

  // ---- 4. Negative cases ----
  console.log("\nRejections:");
  const rejects = async (label: string, fn: () => Promise<unknown>) => {
    try {
      await fn();
      check(false, `${label} (unexpectedly succeeded)`);
    } catch {
      check(true, label);
    }
  };

  await rejects("wrong password rejected", () =>
    decryptFile(ct.slice(0), FIXTURES.password + "wrong", null)
  );
  await rejects("wrong key file rejected", () => {
    const wrongKey = new Uint8Array(64);
    webcrypto.getRandomValues(wrongKey);
    return decryptFile(ctKf.slice(0), FIXTURES.password, wrongKey.buffer as ArrayBuffer);
  });
  await rejects("missing key file rejected", () =>
    decryptFile(ctKf.slice(0), FIXTURES.password, null)
  );
  await rejects("tampered ciphertext rejected (AES-GCM authentication)", () => {
    const tampered = new Uint8Array(ct.slice(0));
    tampered[tampered.length - 1] ^= 0xff;
    return decryptFile(tampered.buffer as ArrayBuffer, FIXTURES.password, null);
  });
  await rejects("tampered salt rejected", () => {
    const tampered = new Uint8Array(ct.slice(0));
    tampered[6] ^= 0xff; // inside the salt
    return decryptFile(tampered.buffer as ArrayBuffer, FIXTURES.password, null);
  });
  await rejects("truncated input rejected", () =>
    decryptFile(ct.slice(0, 20), FIXTURES.password, null)
  );

  // ---- 5. BIP-39 / SeedQR ----
  // Not part of the frozen crypto core, but a wrong word index produces a
  // QR that scans cleanly into the WRONG wallet, which is silent and
  // unrecoverable. Vectors are the canonical BIP-39 English test mnemonics;
  // the SeedQR digit strings follow the SeedSigner Standard SeedQR spec
  // (each index zero-padded to 4 decimal digits).
  console.log("\nBIP-39 validation and Standard SeedQR:");

  const A12 =
    "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about";
  const A24 =
    "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon " +
    "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon art";
  const V18 =
    "gravity machine north sort system female filter attitude volume fold club stay " +
    "feature office ecology stable narrow fog";

  const seedVectors: Array<[string, string, number, string]> = [
    ["12-word", A12, 128, "0".repeat(44) + "0003"],
    ["24-word", A24, 256, "0".repeat(92) + "0102"],
    [
      "18-word",
      V18,
      192,
      "081610681202166017660679069101171966072403531703067312280560169411760722",
    ],
  ];

  for (const [label, mnemonic, bits, seedQr] of seedVectors) {
    const r = await validateBip39(mnemonic);
    check(r.valid, `${label} mnemonic validates`);
    if (!r.valid) continue;
    check(r.entropyBits === bits, `${label} entropy is ${bits} bits`);
    const digits = toStandardSeedQR(r.words);
    check(digits === seedQr, `${label} SeedQR digits match spec`);
    if (digits !== seedQr) {
      console.error(`        expected: ${seedQr}`);
      console.error(`        actual:   ${digits}`);
    }
    check(
      digits.length === r.words.length * 4,
      `${label} SeedQR is ${mnemonic.split(" ").length * 4} digits`
    );
  }

  // Case and whitespace are normalized before lookup.
  const messy = await validateBip39("  ABANDON \t abandon\nabandon " + A12.split(" ").slice(3).join(" ") + " ");
  check(messy.valid, "mixed case and whitespace normalize to a valid mnemonic");

  // Negative cases: each failure reason is reachable and correctly labelled.
  const badChecksum = await validateBip39(A12.replace(/about$/, "abandon"));
  check(
    !badChecksum.valid && badChecksum.reason === "checksum-mismatch" && badChecksum.seedShaped,
    "bad checksum rejected as checksum-mismatch (seed-shaped)"
  );

  const unknownWord = await validateBip39(A12.replace(/about$/, "zzzznotaword"));
  check(
    !unknownWord.valid && unknownWord.reason === "unknown-word" && unknownWord.seedShaped,
    "unknown word rejected as unknown-word (seed-shaped, <=1 unknown)"
  );

  const wrongCount = await validateBip39("abandon about");
  check(
    !wrongCount.valid && wrongCount.reason === "wrong-word-count" && !wrongCount.seedShaped,
    "wrong word count rejected and NOT flagged seed-shaped"
  );

  // toStandardSeedQR must refuse anything not in the wordlist rather than
  // silently emitting a short/garbled payload.
  await rejects("toStandardSeedQR refuses a non-wordlist word", async () =>
    toStandardSeedQR(["abandon", "zzzznotaword"])
  );

  // ---- 6. Standalone recovery file ----
  // site/ittybitz-recovery.html is a single self-contained page that
  // decrypts IttyBitz containers with no dependencies, no network and no
  // build step, so a user can recover their data even if this project,
  // its domain and its author are all gone.
  //
  // It reimplements the container parsing and key derivation, which means it
  // can silently drift from crypto.ts. So it does not get to be trusted on
  // its own claims: the decrypt core is extracted from the HTML and every
  // historical fixture above is replayed through it. If the recovery file
  // and crypto.ts ever disagree about any real ciphertext, this fails.
  console.log("\nStandalone recovery file (site/ittybitz-recovery.html):");

  // This is the only copy of the recovery tool in the repository. It lives in
  // site/, the directory published to GitHub Pages, so it needs no build step to
  // reach ittybitz.app — and no build step here either, which is why this
  // suite's workflow can skip npm ci entirely. Recover/README.md is a pointer
  // to this file, not a second copy of it.
  const recoveryHtml = readFileSync(join(HERE, "..", "site", "ittybitz-recovery.html"), "utf8");
  const coreMatch = recoveryHtml.match(
    /<script id="ittybitz-decrypt-core">([\s\S]*?)<\/script>/
  );
  check(!!coreMatch, "decrypt core block found in the recovery HTML");

  if (coreMatch) {
    const sandbox: any = { crypto: webcrypto, TextEncoder, TextDecoder, console };
    createContext(sandbox);
    runInContext(coreMatch[1]!, sandbox);
    const recoveryDecrypt = sandbox.ittybitzDecrypt;
    check(typeof recoveryDecrypt === "function", "recovery core exposes ittybitzDecrypt()");

    // The recovery file must state the same PBKDF2 iteration count. A
    // mismatch here would decrypt nothing, but catching it by name gives a
    // far clearer failure than a wall of authentication errors.
    check(
      sandbox.ITTYBITZ_PBKDF2_ITERATIONS === 1_000_000,
      "recovery core uses 1,000,000 PBKDF2 iterations"
    );

    if (typeof recoveryDecrypt === "function") {
      let recovered = 0;
      let recoveryFailed = 0;
      for (const fx of FIXTURES.fixtures) {
        try {
          const keyFile = fx.keyFile
            ? new Uint8Array(hexToArrayBuffer(FIXTURES.keyFileHex))
            : null;
          const bytes = new Uint8Array(b64ToArrayBuffer(fx.base64));
          const out = dec.decode(await recoveryDecrypt(bytes, FIXTURES.password, keyFile));
          if (out === fx.plaintext) recovered++;
          else {
            recoveryFailed++;
            console.error(`  FAIL  recovery mismatch on ${fx.version} ${fx.payload}`);
          }
        } catch (err) {
          recoveryFailed++;
          console.error(`  FAIL  recovery threw on ${fx.version} ${fx.payload}: ${(err as Error).message}`);
        }
      }
      check(
        recovered === FIXTURES.fixtures.length && recoveryFailed === 0,
        `recovery file decrypts all ${FIXTURES.fixtures.length} historical fixtures (v0 and v1, with and without key file)`
      );

      // The independently-constructed v0 blob too.
      try {
        const out = dec.decode(
          await recoveryDecrypt(
            new Uint8Array(b64ToArrayBuffer(FIXTURES.independent.base64)),
            FIXTURES.password,
            null
          )
        );
        check(out === FIXTURES.independent.plaintext, "recovery file decrypts the raw-primitive v0 blob");
      } catch (err) {
        check(false, `recovery file on raw-primitive v0 blob — threw: ${(err as Error).message}`);
      }

      // And it must refuse the same things crypto.ts refuses.
      await rejects("recovery file rejects a wrong password", () =>
        recoveryDecrypt(new Uint8Array(ct.slice(0)), FIXTURES.password + "wrong", null)
      );
      await rejects("recovery file rejects a tampered ciphertext", () => {
        const tampered = new Uint8Array(ct.slice(0));
        tampered[tampered.length - 1] ^= 0xff;
        return recoveryDecrypt(tampered, FIXTURES.password, null);
      });
      await rejects("recovery file rejects truncated input", () =>
        recoveryDecrypt(new Uint8Array(ct.slice(0, 20)), FIXTURES.password, null)
      );
    }
  }

  // ---- 7. Standalone two-way app (site/index.html) ----
  // The full single-file IttyBitz encrypts AND decrypts. Like the recovery
  // file it reimplements the container parsing and key derivation, so it is
  // gated the same way — but in BOTH directions: ciphertext it produces must
  // open under crypto.ts, and ciphertext crypto.ts produces must open under
  // it. That two-way guarantee is exactly what a bundled copy of the React
  // app cannot give by inspection, and it is why this file is trustworthy.
  console.log("\nStandalone two-way app (site/index.html):");

  const appHtml = readFileSync(join(HERE, "..", "site", "index.html"), "utf8");
  const appCoreMatch = appHtml.match(/<script id="ittybitz-crypto-core">([\s\S]*?)<\/script>/);
  const appBip39Match = appHtml.match(/<script id="ittybitz-bip39">([\s\S]*?)<\/script>/);
  check(!!appCoreMatch, "crypto core block found in ittybitz.html");
  check(!!appBip39Match, "bip39 block found in ittybitz.html");

  if (appCoreMatch && appBip39Match) {
    const box: any = { crypto: webcrypto, TextEncoder, TextDecoder, console };
    createContext(box);
    runInContext(appCoreMatch[1]!, box);
    runInContext(appBip39Match[1]!, box);
    const appEncrypt = box.ittybitzEncrypt;
    const appDecrypt = box.ittybitzDecrypt;
    check(typeof appEncrypt === "function", "app core exposes ittybitzEncrypt()");
    check(typeof appDecrypt === "function", "app core exposes ittybitzDecrypt()");
    check(
      box.ITTYBITZ_PBKDF2_ITERATIONS === 1_000_000,
      "app core uses 1,000,000 PBKDF2 iterations"
    );

    if (typeof appEncrypt === "function" && typeof appDecrypt === "function") {
      // 7a. Decrypts every historical fixture (v0 and v1, ±key file).
      let appOk = 0;
      let appBad = 0;
      for (const fx of FIXTURES.fixtures) {
        try {
          const keyFileU8 = fx.keyFile ? new Uint8Array(hexToArrayBuffer(FIXTURES.keyFileHex)) : null;
          const out = dec.decode(
            await appDecrypt(new Uint8Array(b64ToArrayBuffer(fx.base64)), FIXTURES.password, keyFileU8)
          );
          if (out === fx.plaintext) appOk++;
          else { appBad++; console.error(`  FAIL  app mismatch on ${fx.version} ${fx.payload}`); }
        } catch (err) {
          appBad++;
          console.error(`  FAIL  app threw on ${fx.version} ${fx.payload}: ${(err as Error).message}`);
        }
      }
      check(
        appOk === FIXTURES.fixtures.length && appBad === 0,
        `app decrypts all ${FIXTURES.fixtures.length} historical fixtures (v0 and v1, with and without key file)`
      );

      // 7b. Cross round-trips — the guarantee this whole file exists to make.
      for (const withKey of [false, true]) {
        const kfHex = FIXTURES.keyFileHex;
        const suffix = withKey ? "key file" : "password only";

        const appMsg = "app->crypto.ts " + withKey;
        const appCt = await appEncrypt(
          enc.encode(appMsg),
          FIXTURES.password,
          withKey ? new Uint8Array(hexToArrayBuffer(kfHex)) : null
        );
        // appEncrypt runs in a vm realm, so appCt.buffer is that realm's
        // ArrayBuffer and fails crypto.ts's `instanceof ArrayBuffer` guard.
        // Uint8Array.from copies the bytes into a main-realm buffer.
        const appCtBuf = Uint8Array.from(appCt).buffer as ArrayBuffer;
        const appCtPt = dec.decode(
          await decryptFile(appCtBuf, FIXTURES.password, withKey ? hexToArrayBuffer(kfHex) : null)
        );
        check(appCtPt === appMsg, `app-encrypted text opens under crypto.ts (${suffix})`);

        const tsMsg = "crypto.ts->app " + withKey;
        const tsCt = await encryptFile(
          enc.encode(tsMsg).buffer as ArrayBuffer,
          FIXTURES.password,
          withKey ? hexToArrayBuffer(kfHex) : null
        );
        const tsCtPt = dec.decode(
          await appDecrypt(
            new Uint8Array(tsCt),
            FIXTURES.password,
            withKey ? new Uint8Array(hexToArrayBuffer(kfHex)) : null
          )
        );
        check(tsCtPt === tsMsg, `crypto.ts-encrypted text opens under app (${suffix})`);
      }

      // 7c. The app produces a well-formed v1 container.
      const appHeader = await appEncrypt(enc.encode("header check"), FIXTURES.password, null);
      check(
        appHeader[0] === 0x49 && appHeader[1] === 0x42 && appHeader[2] === 0x54 &&
          appHeader[3] === 0x5a && appHeader[4] === 0x01,
        "app emits an IBTZ v1 header"
      );

      // 7d. Same rejections as crypto.ts.
      await rejects("app rejects a wrong password", () =>
        appDecrypt(new Uint8Array(ct.slice(0)), FIXTURES.password + "wrong", null)
      );
      await rejects("app rejects a tampered ciphertext", () => {
        const tampered = new Uint8Array(ct.slice(0));
        tampered[tampered.length - 1] ^= 0xff;
        return appDecrypt(tampered, FIXTURES.password, null);
      });
      await rejects("app rejects truncated input", () =>
        appDecrypt(new Uint8Array(ct.slice(0, 20)), FIXTURES.password, null)
      );

      // 7e. BIP-39 parity with src/lib/bip39.ts.
      const appValidate = box.ittybitzValidateBip39;
      const appSeedQr = box.ittybitzToSeedQR;
      for (const [label, mnemonic, bits, seedQr] of seedVectors) {
        const r = await appValidate(mnemonic);
        check(
          r.valid && r.entropyBits === bits && appSeedQr(r.words) === seedQr,
          `app BIP-39 ${label} validates and SeedQR matches spec`
        );
      }
    }
  }

  // ---- Summary ----
  console.log(`\n${passed} passed, ${failures} failed`);
  if (failures > 0) {
    console.error("CRYPTO REGRESSION FAILED — do not ship.\n");
    process.exit(1);
  }
  console.log("All crypto regression checks passed.\n");
}

main().catch((err) => {
  console.error("\nFATAL:", err);
  process.exit(1);
});
